In [ ]:
import pandas as pd
import sqlite3
import requests
from bs4 import BeautifulSoup

In [ ]:
csv_df = pd.read_csv('/content/drive/MyDrive/Datasets/iris.csv')
print("CSV Data:")
print(csv_df.head())

CSV Data:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
excel_df = pd.read_excel('/content/drive/MyDrive/Datasets/heart.xlsx')
print("\nExcel Data")
excel_df.head(5)

Excel Data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
conn = sqlite3.connect('my_database.db')
cursor = conn.cursor()
cursor.execute('''
CREATE TABLE IF NOT EXISTS employees (
  id INTEGER PRIMARY KEY,
  name TEXT,
  department TEXT,
  salary REAL,
  hire_date TEXT
  )
  ''')
cursor.executemany('''
INSERT INTO employees (id, name, department, salary, hire_date) VALUES (?, ?, ?, ?, ?)
''',[
    (1, 'Alice Smith', 'HR', 55000, '2018-05-01'),
    (2, 'Bob Johnson', 'IT', 72000, '2019-07-15'),
    (3, 'Carol White', 'Finance', 68000, '2017-09-30'),
    (4, 'David Brown', 'Marketing', 60000, '2020-02-10'),
    (5, 'Eva Green', 'IT', 75000, '2021-04-25'),
    ])
conn.commit()
print("Database and 'employees' table created with sample data.")
sql_df = pd.read_sql_query("SELECT * FROM employees", conn)
print(sql_df)
conn.close()

Database and 'employees' table created with sample data.
   id         name department   salary   hire_date
0   1  Alice Smith         HR  55000.0  2018-05-01
1   2  Bob Johnson         IT  72000.0  2019-07-15
2   3  Carol White    Finance  68000.0  2017-09-30
3   4  David Brown  Marketing  60000.0  2020-02-10
4   5    Eva Green         IT  75000.0  2021-04-25

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")
html_table = soup.find("table", {"class": "wikitable"})
web_df = pd.read_html(str(html_table))[0]
print("\nWeb Scraped Data:")
print(web_df.head())

Web Scraped Data:
        Location  Population % of world         Date  \
0          World  8232000000       100%  13 Jun 2025
1          India  1417492000      17.3%   1 Jul 2025
2          China  1408280000      17.2%  31 Dec 2024
3  United States   340110988       4.2%   1 Jul 2024
4      Indonesia   284438782       3.5%  30 Jun 2025

  Source (official or from the United Nations) Notes
0                          UN projection[1][3]   NaN
1                       Official projection[4]   [b]
2                         Official estimate[5]   [c]
3                         Official estimate[6]   [d]
4                National annual projection[7]   NaN

/tmp/ipython-input-6-2452979119.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  web_df = pd.read_html(str(html_table))[0]

In [ ]:
if 'date' in csv_df.columns:
    csv_df['date'] = pd.to_datetime(csv_df['date'])
csv_df.to_excel('exported_data.xlsx', index=False)
print("\nData exported to 'exported_data.xlsx' successfully.")

Data exported to 'exported_data.xlsx' successfully.